apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-authenticity-checker-auth
  namespace: aiml
  labels:
    app: video-authenticity-checker-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-authenticity-checker-auth
  template:
    metadata:
      labels:
        app: video-authenticity-checker-auth
    spec:
      nodeSelector:
        instanceType: "neuron"    
      containers:
      - name: video-authenticity-checker-auth
        image: berry2012/video-authenticity-checker:v11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: video-authenticity-service-auth
  namespace: aiml
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing  
    #ssl configuration
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:XXXXXXXXX:certificate/b0c37f83-28ee-4d04-9ff1-61d1fd20c9e8
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"    
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
spec:
  selector:
    app: video-authenticity-checker-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  - port: 443
    protocol: TCP
    targetPort: 8080    
    name: https    
  type: LoadBalancer
